# Generated by Django 4.2.7 on 2023-12-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_storage', '0002_author_slug_book_slug_genre_slug_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='book_storag_title_26a96b_idx',
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug'], name='book_storag_slug_d82034_idx'),
        ),
    ]
